### ISSUE TITLE
Going back to home page button isn't working 

### ISSUE THREAD

**Issue by ZinFinTik** [Zin-And-KNG/MSHelp#1]
Ryder can you fix dis

**Comment by KnightryryV2** [comment]
Work Around but it's kind of tedious. Won't Fix This Directly.

**Comment by KnightryryV2** [comment]
I fixed this directly. if you are going to direct to an index file in a directory use`PATH/TO/DIRECTORY/` (Don't Put index.html inside.) or if you need to go to the root of the website use `/PATH/TO/DIRECTORY/` if using index don't put in index.html in the path if you need more help use [this](https://www.w3schools.com/html/html_filepaths.asp)
